spring:
  application:
    name: bubbleforprofessor

  profiles:
    active: local
    group:
        "prod": "prod, secret"
        "local" : "local, secret"


server:
  port: 8080

logging:
  level:
    org:
      glassfish:
        jaxb: debug
    root: INFO
    com.bubble.buubleforprofessor: DEBUG