spring:
  application:
    name: bubbleforprofessor
  web:
    resources:
      static-locations: file:uploads/
  profiles:
    active: local
    group:
        "prod": "prod, secret"
        "local" : "local, secret"
jwt:
  secret: "ssssssssssssssssssssssssssssssssss"



server:
  port: 8080

# ?? ??
logging:
  level:
    root: INFO
    com.bubble.buubleforprofessor: DEBUG