spring:
  application:
    name: bubbleforprofessor

  profiles:
    active: local
    group:
        "prod": "prod, secret"
        "local" : "local, secret"
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 80   # 최대 활성 연결 수
          max-idle: 20     # 사용하지 않을 때 최대 연결 수
          min-idle: 5      # 최소 유지할 연결 수
          max-wait: 1000ms # 최대 대기 시간

server:
  port: 8080


logging:
  level:
    root: INFO
    com:
      bubble:
        buubleforprofessor: DEBUG