services:
  my-server:
    #도커 컴포즈 파일 기준 도커파일의 위치
    build:
      context: ../
      dockerfile: ./docker/server-container/Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
    depends_on:
      mongodb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - bubble
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SPRING_DATA_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SPRING_DATA_MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${SPRING_DATA_MONGODB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - bubble

  elasticsearch:
    image: elasticsearch:8.15.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node  # 단일 노드 모드로 실행
      - xpack.security.enabled=false  # 보안 비활성화
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data  # 데이터 영속성
    networks:
      - bubble
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


networks:
  bubble:
    driver: bridge

volumes:
  esdata:
